name: CI
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - working-directory: ./src/backend/NSExt
        run: dotnet build -c Release
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: dotnet nuget push ./dist/backend/NSExt/bin/Release/NSExt.${{ github.ref }}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      - run: dotnet nuget push ./dist/backend/NSExt/bin/Release/NSExt.${{ github.ref }}.snupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json