name: CI
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - working-directory: ./src/backend/NSExt
        run: dotnet build -c Release -f net8.0
      - working-directory: ./src/backend/NSExt
        run: dotnet build -c Release -f net9.0
      - working-directory: ./src/backend/NSExt
        run: dotnet pack -c Release --no-build
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - run: dotnet nuget push ./dist/backend/NSExt/bin/Release/NSExt.${{ steps.get_version.outputs.VERSION }}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json